version: "3.3"

services:
  ws:
    build: .
    volumes:
      - ./src:/usr/src/app/
    ports:
      - "8003:8000"
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_URI: mysql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - do-flask-social-data:/var/lib/mysql

volumes:
  do-flask-social-data:
